# Generated by Django 3.0.2 on 2020-01-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_address', models.CharField(max_length=255)),
                ('applicant_phone', models.IntegerField()),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_birth_cert', models.FileField(upload_to='')),
                ('applicant_national_id', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.TextField()),
                ('recommendation_letter', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantSchoolInfo',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='applicant_school_info', serialize=False, to='sponsorship.Applicant')),
                ('school_name', models.CharField(max_length=255)),
                ('school_address', models.CharField(max_length=255)),
                ('academic_level', models.CharField(max_length=255)),
                ('year_of_completion', models.IntegerField()),
            ],
        ),
    ]
